# Generated by Django 5.2.5 on 2025-09-01 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tutor_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('video_file', models.FileField(blank=True, null=True, upload_to='media/courses/')),
                ('tutor', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='tutors_course', to='tutor_management.tutor')),
            ],
        ),
    ]
