# Generated by Django 5.2.5 on 2025-09-01 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
        ('student_management', '0002_alter_student_level'),
        ('tutor_management', '0002_alter_tutor_subjects_taught'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(related_name='courses', to='student_management.student'),
        ),
        migrations.AlterField(
            model_name='course',
            name='tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutors_course', to='tutor_management.tutor'),
        ),
        migrations.AlterField(
            model_name='course',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='courses/'),
        ),
    ]
