# Generated by Django 5.2.5 on 2025-09-01 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student_management', '0001_initial'),
        ('tutor_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expectations', models.TextField(blank=True)),
                ('students', models.ManyToManyField(null=True, related_name='booked_sessions', to='student_management.student')),
                ('tutor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tutor_management.tutor')),
            ],
        ),
    ]
