# Generated by Django 5.2.5 on 2025-09-19 09:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor_management', '0002_alter_tutor_subjects_taught'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutor',
            name='subjects_taught',
        ),
        migrations.AddField(
            model_name='tutor',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='tutor',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tutor',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='tutors/'),
        ),
        migrations.AddField(
            model_name='tutor',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='tutor',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
